import "dotenv/config"
export const DATABASE_URL = process.env.DATABASE_URL;
export const ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET;
export const REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET;
export const CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME;
export const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY;
export const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET;
export const CLOUDINARY_FOLDER = process.env.CLOUDINARY_FOLDER;
export const REDIS_URL = process.env.REDIS_URL;
export const RESEND_API_KEY = process.env.RESEND_API_KEY;
export const RESEND_FROM_EMAIL = process.env.RESEND_FROM_EMAIL;
export const APP_URL = process.env.APP_URL;
export const BACKEND_URL = process.env.BACKEND_URL;
export const NODE_ENV = process.env.NODE_ENV;

console.log({
    DATABASE_URL: DATABASE_URL,
    ACCESS_TOKEN_SECRET: ACCESS_TOKEN_SECRET,
    REFRESH_TOKEN_SECRET: REFRESH_TOKEN_SECRET,
    CLOUDINARY_CLOUD_NAME: CLOUDINARY_CLOUD_NAME,
    CLOUDINARY_API_KEY: CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET: CLOUDINARY_API_SECRET,
    CLOUDINARY_FOLDER: CLOUDINARY_FOLDER,
    REDIS_URL: REDIS_URL,
    RESEND_API_KEY: RESEND_API_KEY,
    RESEND_FROM_EMAIL: RESEND_FROM_EMAIL,
    APP_URL: APP_URL,
    BACKEND_URL: BACKEND_URL
})